### ISSUE TITLE
Optional exception breakpoints

### ISSUE THREAD

**Issue by ghost** [castwide/vscode-ruby-debug#15]
Currently call stack monitor would pause on every exception (including handled)
This renders the debugger useless for me as  I need to cycle through (+50 for my application) automatically generated breakpoints, before execution even reaches my application code.
For example adding something like that in app will trigger breakpoint 3 times
`require 'csv'`

**Comment by castwide** [comment]
Version 1.4.0 of the [Readapt gem](https://github.com/castwide/readapt) makes exception breakpoints optional. The debug panel has a checkbox to enable them (off by default).
