### ISSUE TITLE
Sinatra

### ISSUE THREAD

**Issue by wahmedswl** [castwide/vscode-ruby-debug#2]
Hi, trying to debug sintra app with ruby-debug ext but it closes immediately. Would be great if share eg config for Sinatra also.

Thanks

**Comment by castwide** [comment]
I've been using the extension to debug a Sinatra app of my own, so I can at least confirm that it works. Can you post your launch config?

**Comment by wahmedswl** [comment]
Hi, thanks for quick reply

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ruby-debug",
            "request": "launch",
            "name": "Active File",
            "program": "${file}",
            "programArgs": [],
            "useBundler": true
        }
    ]
}
```

**Comment by wahmedswl** [comment]
Hi, i have also tried

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ruby-debug",
            "request": "launch",
            "name": "Active File",
            "program": "${file}",
            "programArgs": [
                "config.ru"
            ],
            "useBundler": true
        }
    ]
}
```

both way, it shows this warning and debugger session closed

```
WARNING: If you plan to load any of ActiveSupport's core extensions to Hash, be
sure to do so *before* loading Sinatra::Application or Sinatra::Base. If not,
you may disregard this warning.

Set SINATRA_ACTIVESUPPORT_WARNING=false in the environment to hide this warning.

```

**Comment by castwide** [comment]
I suspect at least part of the problem is the `program` property. Setting it to `${file}` will start the debugger with whichever file currently has focus in the editor. You probably want to set it to the executable that starts the server.

If you can tell me what command you would use to start the server from a command line, I might be able translate it into a working configuration.

**Comment by wahmedswl** [comment]
Hi, i use following command to run the server
```bundle exec rackup -o 0.0.0.0 -p 9292```

Thanks

**Comment by castwide** [comment]
This launch configuration might work:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ruby-debug",
            "request": "launch",
            "name": "Run Rackup",
            "program": "rackup",
            "programArgs": [
                "-o",
                "0.0.0.0",
                "-p",
                "-9292"
            ],
            "useBundler": true
        }
    ]
}
```

* The `program` argument should know how to start `rackup` since it's part of your bundle.
* The `programArgs` are everything else you would normally pass on the command line.
* `useBundler: true` should ensure the debugger runs under the same context as `bundle exec`.
* The `name` argument is totally arbitrary. It can be any descriptive title for what the configuration does.

If you still run into problems, please let me know.

**Comment by wahmedswl** [comment]
Hi, tried provided config but i am getting 

![image](https://user-images.githubusercontent.com/15020561/70986026-f09ef800-20de-11ea-8fdd-286f5ec997df.png)

**Comment by castwide** [comment]
That message can be a little misleading. It indicates that the debugger failed to start, but is often incorrect about the reason. I'm working on error handling to provide more accurate descriptions.

You might have a zombie process running that's blocking the Readapt port. Try running `ps ax | grep readapt` and killing any existing processes (or just reboot the machine for a brute force solution).

I'm also working on fixing zombie processes for the next gem release. Related issue; https://github.com/castwide/readapt/issues/3

**Comment by wahmedswl** [comment]
thanks, that was the issue and there was also a minor typo. This is final ```launch.json```

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ruby-debug",
            "request": "launch",
            "name": "Run Rackup",
            "program": "rackup",
            "programArgs": [
                "-o",
                "0.0.0.0",
                "-p",
                "9292"
            ],
            "useBundler": true
        }
    ]
}
```
