### ISSUE TITLE
Breakpoints are not fired in a rack-app

### ISSUE THREAD

**Issue by qortex** [castwide/vscode-ruby-debug#6]
I use rack-app (small layer on top of rack). So basically my app is a bare rack app.

I launch it through puma, and my debug config is:
```json
{
      "type": "ruby-debug",
      "request": "launch",
      "name": "Launch server",
      "program": "puma",
      "programArgs": ["--config", "config/puma/development.rb", "--environment", "development", "config.ru"],
      "useBundler": false
    }
```

It launches ok and requests are served.
But breakpoints do not stop execution.

How can I debug to see where it comes from?

I have no multi-threading or workers on puma, here is the puma config file:
```ruby
threads_count = 1
threads threads_count, threads_count

port ENV.fetch('PORT') { 9292 }

workers 0
```

**Comment by qortex** [comment]
Debugger works well when on a bare file though (through the `file` debugger config).

**Comment by castwide** [comment]
Is it possible that Puma starts `config.ru` in a separate process? That would explain why it's not attached to the debugger.

**Comment by qortex** [comment]
Yeah that's a possibility I guess.
I have left Rails and now use bare rack with Puma, breakpoints work well in that setting.

So the issue might be located in the way Rails launches Puma by default.

**Comment by qortex** [comment]
I actually got it to work with that config but don't remember the details of why it works (doesn't use the same debugger?):
```
{
      "name": "Qontrol server",
      "type": "Ruby",
      "request": "launch",
      "program": "bin/puma",
      "args": [
        "--config", "config/puma/development.rb", "--environment", "development", "config.ru"
      ]
    },
```
And have:
```
gem 'debase'
gem 'ruby-debug-ide'
```
