### ISSUE TITLE
Config launch.json on sinatra app

### ISSUE THREAD

**Issue by erikson879** [castwide/vscode-ruby-debug#8]
Hi, how to should do configuring to sinatra app?

{
            "type": "ruby-debug",
            "request": "launch",
            "name": "SEGQL",
            "program": "${workspaceFolder}/project.rb",
            "programArgs": [
                "-o",
                "127.0.0.1",
                "-p",
                "4567"
            ],
            "useBundler": true
        }

I have above configurations

but when I play this debug, it show debug panel and close in one segund.

**Comment by castwide** [comment]
Is the `readapt` gem in your Gemfile?

Does it work when you run `bundle exec ruby project.rb` from the command line?

**Comment by erikson879** [comment]
Thank @castwide,

Yes, only I reboot my vsc and and my session and work.

Thank a lot.
